name: Node CI

on:
  push:
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix.node-version }}
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
      - name: Prepare Environment
        run: |
          npm install
        env:
          CI: true
      - name: Run Biome
        run: biome ci .
      - name: lint
        run: |
          npm run lint
      - name: check
        run: |
          npm run check
      - name: Test jest
        run: |
          npm run test:verbose
        env:
          CI: true
          FORCE_COLOR: 2
